ARG AIRFLOW_IMAGE_NAME="2.2.3-python3.8"

FROM "apache/airflow:${AIRFLOW_IMAGE_NAME}"

# - Install GCP util
RUN curl -sSL https://sdk.cloud.google.com | bash
ENV PATH $PATH:/home/airflow/google-cloud-sdk/bin


# - Install dependencies
CMD echo "Installing dependencies"

ADD requirements.txt /tmp/requirements.txt
ADD requirements.extra.txt /tmp/requirements.extra.txt
RUN pip3 install --no-deps -r /tmp/requirements.txt -r /tmp/requirements.extra.txt