.SILENT: ;
BROKKR_PLUGINS := airflow/airflow@34b389a help/help@c09a208
.DEFAULT_GOAL := help

# Hack for local testing. This would be installed by the install script instead
-include ../../brokkr/brokkr.mk